<?php
// === CONFIG ===
$botToken  = "8311328395:AAFZn0ljyLwZu1mTOkMJMMgcsppufJ5g_JE";
$apiURL    = "https://api.telegram.org/bot$botToken/";
$owner     = "tradingrobots-web";
$repo2     = "ex5s"; // repo containin

// === FUNCTIONS ===
function send_msg($apiURL, $chat_id, $text, $keyboard = null) {
    $data = [
        'chat_id' => $chat_id,
        'text' => $text,
        'parse_mode' => 'Markdown'
    ];
    if ($keyboard) $data['reply_markup'] = json_encode($keyboard);

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $apiURL . "sendMessage");
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_exec($ch);
    curl_close($ch);
}

function send_document($apiURL, $chat_id, $file_path, $caption = "") {
    $ch = curl_init();
    $cfile = new CURLFile(realpath($file_path));
    $data = [
        'chat_id' => $chat_id,
        'document' => $cfile,
        'caption' => $caption,
        'parse_mode' => 'Markdown'
    ];
    curl_setopt($ch, CURLOPT_URL, $apiURL . "sendDocument");
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_exec($ch);
    curl_close($ch);
}

// ✅ Fixed version for large binary files
function github_download_file($owner, $repo, $path, $destination) {
    $url = "https://raw.githubusercontent.com/$owner/$repo/main/" . rawurlencode($path);

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/5.0");
    curl_setopt($ch, CURLOPT_HEADER, false);

    $data = curl_exec($ch);
    $status = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $contentType = curl_getinfo($ch, CURLINFO_CONTENT_TYPE);
    curl_close($ch);

    if ($status == 200 && strpos($contentType, 'text/html') === false) {
        file_put_contents($destination, $data, LOCK_EX);
        return true;
    }
    return false;
}

// === MAIN ===
$content = file_get_contents("php://input");
$update  = json_decode($content, true);
if (!$update) exit;

$chat_id = $update["message"]["chat"]["id"];
$text    = trim($update["message"]["text"] ?? "");

// === KEYBOARD ===
$mainKeyboard = [
    "keyboard" => [
        [["text" => "⬇️ Download Indicator & Script"]],
        [["text" => "⬅️ Back to Menu"]],
    ],
    "resize_keyboard" => true
];

// === START HANDLER ===
if ($text == "/start" || $text == "⬅️ Back to Menu") {
    send_msg($apiURL, $chat_id,
        "👋 *Welcome to KingDiv Tools!*\n\n"
      . "Tap the button below to download your latest *Indicator* and *Activator Script* files 📦👇",
        $mainKeyboard
    );
    exit;
}

// === DOWNLOAD HANDLER ===
if ($text == "⬇️ Download Indicator & Script") {
    $indicator_file = __DIR__ . "/Kingdiv V1 2025.ex5";
    $script_file    = __DIR__ . "/KingDiv_Activator_Script 2.ex5";

    if (!file_exists($indicator_file)) {
        github_download_file($owner, $repo2, "Kingdiv V1 2025.ex5", $indicator_file);
    }
    if (!file_exists($script_file)) {
        github_download_file($owner, $repo2, "KingDiv_Activator_Script 2.ex5", $script_file);
    }

    if (filesize($indicator_file) < 1000) {
    send_msg($apiURL, $chat_id,
        "⚠️ *Download Interrupted*\n\n"
      . "It seems your *Indicator file* didn’t download correctly.\n"
      . "Please tap again or retry in a few moments — your premium tools are standing by."
    );
} else {
    send_document($apiURL, $chat_id, $indicator_file,
        "📈 *KingDiv V1 2025 Indicator* — your *High-Precision Chart Analysis Engine.*\n\n"
      . "Built for *Forex*, *Volatility Indices*, and *Step Index* — where milliseconds and micro-trends define the edge.\n\n"
      . "💎 *What Makes It Special:*\n"
      . "• Institutional-grade chart analytics powered by adaptive logic ⚙️\n"
      . "• Real-time bias detection for *trend confidence* 📊\n"
      . "• Dynamic Support & Resistance channels auto-generated by market structure 🔍\n"
      . "• *No hidden settings. No coding. Plug, activate, and analyze instantly.*\n\n"
      . "When precision meets simplicity — trading stops being guessing and becomes *execution.* 🚀"
    );
}

if (filesize($script_file) < 1000) {
    send_msg($apiURL, $chat_id,
        "⚠️ *Activator Script Missing*\n\n"
      . "Your *Activation Script* didn’t finish downloading.\n"
      . "Please retry — this script securely unlocks your KingDiv license."
    );
} else {
    send_document($apiURL, $chat_id, $script_file,
        "⚙️ *KingDiv Activator Script 2* — *Activate and Analyze Instantly.*\n\n"
      . "🔐 Run it once in *MetaTrader → Scripts* to bind your premium license to your verified Binance alias.\n\n"
      . "💡 After activation, your indicator automatically syncs — ready to decode market structure and deliver precise signals in real time.\n\n"
      . "Designed for serious traders mastering *Forex*, *Volatility 75*, and *Step Index* movements — where accuracy means profit.\n\n"
      . "Activate. Analyze. Dominate. 💼"
    );
}


    exit;
}
?>
